In [5]:
import numpy as np

tableau = np.array([4, 2, 0])               # Creation d'un tableau
print(type(tableau))                         # Affichage du type
print(tableau.shape)                        # Affichage de la taille (longueur et largeur)
print(tableau[0], tableau[1], tableau[2])   # Acces aux valeurs 
tableau[0] = 5                              # Affectation d'une valeur
print(tableau)                              # Affichage du tableau

matrice = np.array([[1,2,3],[4,5,6]])                # Creation d'une matrice 2x3
print(matrice.shape)                                 # Affichage de la taille (longueur et largeur)
print(matrice[0, 0], matrice[0, 1], matrice[1, 0])   # Affichage des valeurs



<class 'numpy.ndarray'>
(3,)
4 2 0
[5 2 0]
(2, 3)
1 2 4


In [7]:
import numpy as np

a = np.zeros((2,2))  # Creation d'una matrice 2 x 2 de zeros
print(a)             
                     
    
b = np.ones((1,2))   # Creation d'une matrice 1x2 de 1 
print(b)             

c = np.full((2,2), 7) # Creation d'une matrice 2x2 de valeur constantes de 7 
print(c)               
                      

d = np.eye(2)        # Creation d'une matrice 2x2 
print (d)              
                     
    
e = np.random.random((2,2)) # Creation d'une matrice 2x2 avec des valeurs aleatoires
print(e)                     
 

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[ 7.  7.]
 [ 7.  7.]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.56526582  0.90538346]
 [ 0.19830948  0.12357486]]


/usr/lib/python3/dist-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((2, 2), 7) will return an array of dtype('int32')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


In [9]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)




print (x + y)
print (np.add(x, y))



print (x - y)
print (np.subtract(x, y))



print (x * y)
print(np.multiply(x, y))


print (x / y)
print (np.divide(x, y))


print (np.sqrt(x))



[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [10]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])


print(v.dot(w))
print(np.dot(v, w))


print(x.dot(v))
print(np.dot(x, v))



print(x.dot(y))
print(np.dot(x, y))



219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [11]:
import numpy as np

x = np.array([[1,2],[3,4]])

print (np.sum(x))
print (np.sum(x, axis=0))
print (np.sum(x, axis=1))



10
[4 6]
[3 7]
